// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    appId: '1:549314038522:web:c2116f8d64cf30752e9743',
    messagingSenderId: '549314038522',
    projectId: 'mobileprogramming-ea83a',
    authDomain: 'mobileprogramming-ea83a.firebaseapp.com',
    databaseURL: 'https://mobileprogramming-ea83a-default-rtdb.firebaseio.com',
    storageBucket: 'mobileprogramming-ea83a.firebasestorage.app',
    measurementId: 'G-0WTGXJZ9K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:549314038522:android:430aa67623825abc2e9743',
    messagingSenderId: '549314038522',
    projectId: 'mobileprogramming-ea83a',
    databaseURL: 'https://mobileprogramming-ea83a-default-rtdb.firebaseio.com',
    storageBucket: 'mobileprogramming-ea83a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    appId: '1:549314038522:ios:36943485122a1a632e9743',
    messagingSenderId: '549314038522',
    projectId: 'mobileprogramming-ea83a',
    databaseURL: 'https://mobileprogramming-ea83a-default-rtdb.firebaseio.com',
    storageBucket: 'mobileprogramming-ea83a.firebasestorage.app',
    iosBundleId: 'com.example.healthyLifeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    appId: '1:549314038522:ios:36943485122a1a632e9743',
    messagingSenderId: '549314038522',
    projectId: 'mobileprogramming-ea83a',
    databaseURL: 'https://mobileprogramming-ea83a-default-rtdb.firebaseio.com',
    storageBucket: 'mobileprogramming-ea83a.firebasestorage.app',
    iosBundleId: 'com.example.healthyLifeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    appId: '1:549314038522:web:49cd38746f4418c42e9743',
    messagingSenderId: '549314038522',
    projectId: 'mobileprogramming-ea83a',
    authDomain: 'mobileprogramming-ea83a.firebaseapp.com',
    databaseURL: 'https://mobileprogramming-ea83a-default-rtdb.firebaseio.com',
    storageBucket: 'mobileprogramming-ea83a.firebasestorage.app',
    measurementId: 'G-HBZVHDMPW7',
  );
}
